In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import requests
from bs4 import BeautifulSoup
import re

In [2]:
def augment(xold,yold,numsteps):
    xnew = []
    ynew = []
    for i in range(len(xold)-1):
        difX = xold[i+1]-xold[i]
        stepsX = difX/numsteps
        difY = yold[i+1]-yold[i]
        stepsY = difY/numsteps
        for s in range(numsteps):
            xnew = np.append(xnew,xold[i]+s*stepsX)
            ynew = np.append(ynew,yold[i]+s*stepsY)
    return xnew,ynew

In [3]:
city1 = input("Please enter a city (all lowercase): ")
city2 = input("Please enter a city (all lowercase): ")
city3 = input("Please enter a city (all lowercase): ")
cities = [city1, city2, city3]

Please enter a city (all lowercase): portland
Please enter a city (all lowercase): seattle
Please enter a city (all lowercase): boston

In [4]:
def make_df(i):
    # data extraction and data cleaning
    r = requests.get('http://worldpopulationreview.com/us-cities/' + cities[i] + '-population/')
    c = r.content
    soup = BeautifulSoup(c, "lxml")
    soup
    main_content = soup.find('div', attrs = {'class': 'section-container clearfix'})
    main_content
    rows = main_content.find_all('tr')
    year = []
    pop = []
    rows = rows[1:]
    for row in rows:
        row_td = row.find_all('td')
        str_cells = str(row_td)
        cleantext = BeautifulSoup(str_cells, "lxml").get_text()
        cleantext = cleantext[1:-1]
        text = cleantext.split(', ')
        year.append(int(text[0]))
        pop.append(int(text[1].replace(',', '')))

    #make dataframe
    cities[i] = (cities[i])[0].upper() + (cities[i])[1::]
    x = np.array(year)
    y = np.array(pop)
    XN,YN = augment(x,y,10)
    data = {'Population': YN, 'Year': XN}
    augmented = pd.DataFrame(data, columns = ['Year', 'Population'])
    df1 = augmented
    df1 = df1[::-1]
    return df1

# make a separate dataframe for each city
dfs = []
for i in range(3):
    dfs.append(make_df(i))

In [6]:
from functools import reduce
df_final = reduce(lambda left,right: pd.merge(left,right,on='Year'), dfs)
df_final

       Year  Population_x  Population_y  Population
0    1871.0        9221.4        1343.3    261757.3
1    1872.0       10149.8        1586.6    272988.6
2    1873.0       11078.2        1829.9    284219.9
3    1874.0       12006.6        2073.2    295451.2
4    1875.0       12935.0        2316.5    306682.5
5    1876.0       13863.4        2559.8    317913.8
6    1877.0       14791.8        2803.1    329145.1
7    1878.0       15720.2        3046.4    340376.4
8    1879.0       16648.6        3289.7    351607.7
9    1880.0       17577.0        3533.0    362839.0
10   1881.0       20457.8        7463.4    371402.8
11   1882.0       23338.6       11393.8    379966.6
12   1883.0       26219.4       15324.2    388530.4
13   1884.0       29100.2       19254.6    397094.2
14   1885.0       31981.0       23185.0    405658.0
15   1886.0       34861.8       27115.4    414221.8
16   1887.0       37742.6       31045.8    422785.6
17   1888.0       40623.4       34976.2    431349.4
18   1889.0       43504.2       38906.6    439913.2
19   1890.0       46385.0       42837.0    448477.0
20   1891.0       50789.1       46620.4    459718.5
21   1892.0       55193.2       50403.8    470960.0
22   1893.0       59597.3       54187.2    482201.5
23   1894.0       64001.4       57970.6    493443.0
24   1895.0       68405.5       61754.0    504684.5
25   1896.0       72809.6       65537.4    515926.0
26   1897.0       77213.7       69320.8    527167.5
27   1898.0       81617.8       73104.2    538409.0
28   1899.0       86021.9       76887.6    549650.5
29   1900.0       90426.0       80671.0    560892.0
..      ...           ...           ...         ...
190  2015.1      632698.7      690391.4    671758.9
191  2015.2      633858.4      692626.8    672726.8
192  2015.3      635018.1      694862.2    673694.7
193  2015.4      636177.8      697097.6    674662.6
194  2015.5      637337.5      699333.0    675630.5
195  2015.6      638497.2      701568.4    676598.4
196  2015.7      639656.9      703803.8    677566.3
197  2015.8      640816.6      706039.2    678534.2
198  2015.9      641976.3      708274.6    679502.1
199  2016.0      643136.0      710510.0    680470.0
200  2016.1      643685.4      712419.1    681250.6
201  2016.2      644234.8      714328.2    682031.2
202  2016.3      644784.2      716237.3    682811.8
203  2016.4      645333.6      718146.4    683592.4
204  2016.5      645883.0      720055.5    684373.0
205  2016.6      646432.4      721964.6    685153.6
206  2016.7      646981.8      723873.7    685934.2
207  2016.8      647531.2      725782.8    686714.8
208  2016.9      648080.6      727691.9    687495.4
209  2017.0      648630.0      729601.0    688276.0
210  2017.1      649078.5      731136.4    688906.7
211  2017.2      649527.0      732671.8    689537.4
212  2017.3      649975.5      734207.2    690168.1
213  2017.4      650424.0      735742.6    690798.8
214  2017.5      650872.5      737278.0    691429.5
215  2017.6      651321.0      738813.4    692060.2
216  2017.7      651769.5      740348.8    692690.9
217  2017.8      652218.0      741884.2    693321.6
218  2017.9      652666.5      743419.6    693952.3
219  2018.0      653115.0      744955.0    694583.0

[220 rows x 4 columns]

In [7]:
Writer = animation.writers['ffmpeg']
writer = Writer(fps=len(df_final)/2, metadata=dict(artist='Me'), bitrate=1800)

In [ ]:
fig, ax = plt.subplots(figsize=(10, 6))
plt.xlim((df_final['Year'])[0], (df_final['Year'])[len(df_final)-1])
plt.ylim(min(df_final[['Population_x','Population_y', 'Population']].min(axis=1)), max(df_final[['Population_x','Population_y', 'Population']].max(axis=1)))
plt.title('Population Growth',fontsize=20)

def animate(j):
    if (j == len(df_final) - 1):
        data = df_final.iloc[:int(j+1)] #select data range
        p = sns.lineplot(x=data['Year'], y=data['Population_x'], data=data, color="b", label=cities[0])
        p.tick_params(labelsize=14)
        plt.setp(p.lines,linewidth=2)
        q = sns.lineplot(x=data['Year'], y=data['Population_y'], data=data, color="r", label=cities[1])
        plt.setp(q.lines, linewidth=2)
        r = sns.lineplot(x=data['Year'], y=data['Population'], data=data, color="g", label=cities[2])
        plt.setp(r.lines, linewidth=2)
        ax.legend(handles=(p, q, r))
    else:
        data = df_final.iloc[:int(j+1)] #select data range
        p = sns.lineplot(x=data['Year'], y=data['Population_x'], data=data, color="b")
        p.tick_params(labelsize=14)
        plt.setp(p.lines,linewidth=2)
        q = sns.lineplot(x=data['Year'], y=data['Population_y'], data=data, color="r")
        plt.setp(q.lines, linewidth=2)
        r = sns.lineplot(x=data['Year'], y=data['Population'], data=data, color="g")
        plt.setp(r.lines, linewidth=2)
    
plt.xlabel('Year',fontsize=16)
plt.ylabel('Population',fontsize=16)
ani = animation.FuncAnimation(fig, animate, frames=len(df_final), repeat=True)
ani.save('test.gif', writer='imagemagick', fps=50)